### ISSUE TITLE
Per-track format configuration in IMG.CFG

### ISSUE THREAD

**Issue by mikewbrantley** [keirf/FlashFloppy#378] opened 2020-10-06 00:19 UTC
Add new options to FlashFloppy img.cfg to support single density on track zero and double density on other tracks.  
This should provide a separate configuration for single and double density.  In other words, track zero would have configuration options and tracks 1 upward would have it's own configuration options.

**Comment by mikewbrantley** [comment] 2020-10-06 16:04
[hfe files.zip](https://github.com/keirf/FlashFloppy/files/5335177/hfe.files.zip)
These are the 3 files I emailed you.

**Comment by keirf** [comment] 2020-10-06 18:49
The FLEX formatted HFE has 10*256b sectors per track, cylinder 0, FM recording. Sectors are numbered 1-20 (across both sides) and have interleave 4:1, and that extends across to side 1 (sector id 11 is the second sector on side 1).

Cylinders > 0: 18*256b sectors per track, MFM recording. Sectors are numbered 1-36 (across both sides) and have interleave 6:1, and that extends across to side 1 (sector id 19 is the sixth sector on side 1).

The DSK looks to be all MFM, as it is 737,280 bytes. I would expect a DSK with FM track0 to be 733,184 bytes. Also intyeresting to note that some FLEX docs mention that track0 has no sector1 and has a sector0 instead. That isn't the case in the HFE image here! Perhaps there is variation in FLEX disk format across different systems running FLEX?

**Comment by mikewbrantley** [comment] 2020-10-06 19:55
The physical disk that is formatted with Flex has Track 0 starting with sector 1 and goes through sector 10 on side one.  Side two starts with sector 11 and goes through sector 20.  This is FM recording.  Tracks 1 through 79 are recorded with MFM and has 18 sectors per side. 

I will get in touch with Mike Evenson and ask about the dsk file formatting he does with the emulator tool.  Now that I think about it, the only time I ever use this tool is to build a dsk file for storage and to extract files from it.  The flashfloppy emulator is the first time I have ever tried extracting these files from anything other than Mike's utility.  I'm sorry for making this so confusing by expecting the emulator tool to perform just as the Flex formatter.

**Comment by keirf** [comment] 2020-10-06 21:07
Here is another DSK sent by @mikewbrantley. This one is formatted with FM track 0. Note that it is still 720k. Cylinder 0 is padded out to 36*256-byte size by 16 unused sectors (file offsets 0x1400-0x2400). Note that the space allocation and padding seems to be done per cylinder, not per track. ie. the DSK file logically comprises 80 9kB cylinders, rather than 160 4.5kB tracks.

This ought to be somehow made configurable in IMG.CFG...

[BB184.zip](https://github.com/keirf/FlashFloppy/files/5336724/BB184.zip)

**Comment by keirf** [comment] 2020-10-06 21:13
For our information, roughly speaking the IMG.CFG geometry should be something like the following. Actually the image and its geometry can't yet be precisely described. I will edit the following as I extend the IMG.CFG options.
```
[default]
cyls = 80
heads = 2
bps = 256
secs = 18
mode = mfm
interleave = 6
id = 1:19
tracks = 0.*
    secs = 10
    mode = fm
    interleave = 4
    id = 1:11
```

**Comment by drdpj** [comment] 2020-10-06 21:52
Here you go!

[480ZBOOT.IMD.zip](https://github.com/keirf/FlashFloppy/files/5337035/480ZBOOT.IMD.zip)

**Comment by mikewbrantley** [comment] 2020-10-06 21:52
Looks good.  It will give us something to experiment with.

**Comment by mikewbrantley** [comment] 2020-10-08 21:00
Michael Evenson developed a program to create a dsk image with 10 sectors per side on track 0 and 18 per side on tracks 1 through 79.  I am attaching the file I created using this software.  Does it look correct now?

[TEST.zip](https://github.com/keirf/FlashFloppy/files/5351269/TEST.zip)

**Comment by keirf** [comment] 2020-10-08 21:11
Hi yes it does. However an earlier DSK you sent also looked formatted correctly: BB184.dsk. But that one had track 0 padded out to same size as other tracks (0x2400 bytes). Whereas this new TEST.DSK has track 0 taking only 0x1400 bytes. So.... to pad or not to pad? Does it matter to FLEX utilities either way (can any of them handle the mixed density)?

**Comment by mikewbrantley** [comment] 2020-10-08 21:31
The software that runs on the PC and creates the dsk file can handle either padded or not but the actual computer that will be accessing flashfloppy will not work with the padded track zero.  It expects track zero to be 10 sectors per side.  I have tried using a padded dsk file and the computer fails with a disk read error.  I will play around with it some more but so far it does not like the padded track.  Of course, the padding I did was on a floppy with double density beyond track zero which is not supported presently.  I will build a single density floppy with padded sectors on track zero and see how that works.

**Comment by keirf** [comment] 2020-10-08 22:13
The DSK files will not yet work on FlashFloppy, padded or not. The question was whether FLEX tools cared. Apparently not. In which case no padding will be easier to get working with FlashFloppy probably.

**Comment by keirf** [comment] 2020-10-09 08:54
This in progress on branch `imgcfg`. Done some code rearranging, mainly now need to add the new `tracks=` option and also allow interleave and sector numbering to be continuous across sides of the disk.

**Comment by mikewbrantley** [comment] 2020-10-09 11:45
Thanks for your support and generosity in working on this.  If changing config for dsk type images, we could name this configuration something else like gti.

-------- Original message --------From: Keir Fraser <notifications@github.com> Date: 10/9/20  4:54 AM  (GMT-05:00) To: keirf/FlashFloppy <FlashFloppy@noreply.github.com> Cc: mikewbrantley <cataula0@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [keirf/FlashFloppy] Per-track format configuration in IMG.CFG (#378) 
This in progress on branch imgcfg. Done some code rearranging, mainly now need to add the new tracks= option and also allow interleave and sector numbering to be continuous across sides of the disk.

**Comment by keirf** [comment] 2020-10-09 15:05
Okay, here is a new firmware for you to try. This should work with images of the unpadded form. You can use the IMG.CFG file in the examples/ subfolder: Just copy it to the root of your USB stick. In this case your flex image must have a filename ending in `.flex.img` or `.flex.dsk`, in order to match the `[flex]` tag defined in IMG.CFG. Note the firmware version number is bumped to v3.100 so you can tell you're running the correct modified version.

Let me know how it goes!

[ff_378_1.zip](https://github.com/keirf/FlashFloppy/files/5355809/ff_378_1.zip)

**Comment by mikewbrantley** [comment] 2020-10-09 16:50
Thanks Keir, I am away from house right now.  Should be back in couple of hours.  

-------- Original message --------From: Keir Fraser <notifications@github.com> Date: 10/9/20  11:05 AM  (GMT-05:00) To: keirf/FlashFloppy <FlashFloppy@noreply.github.com> Cc: mikewbrantley <cataula0@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [keirf/FlashFloppy] Per-track format configuration in IMG.CFG (#378) 
Okay, here is a new firmware for you to try. This should work with images of the unpadded form. You can use the IMG.CFG file in the examples/ subfolder: Just copy it to the root of your USB stick. In this case your flex image must have a filename ending in .flex.img or .flex.dsk, in order to match the [flex] tag defined in IMG.CFG. Note the firmware version number is bumped to v3.100 so you can tell you're running the correct modified version.
Let me know how it goes!
ff_378_1.zip

**Comment by mikewbrantley** [comment] 2020-10-09 18:37
I installed firmware which shows v3.100 on my oled.  I placed two files formatted with no pads on track 0, just 20 sectors.  I named one of these TEST.FLEX.DSK and the other TEST2.FLEX.IMG.  I also placed a BLANK.DSK file formatted for double sided, single density and 80 tracks with no pads.  The two files ending in FLEX.DSK and FLEX.IMG both give an ERR 31.  The one file named BLANK.DSK does not give an error but when I try to format it, I get a disk read error afterwards.  I am sure this is because the img.cfg file does not contain configuration for that file. Attached is the IMG.CFG I am using.

**Comment by keirf** [comment] 2020-10-09 18:50
You didn't attach your IMG.CFG but if it's the one I included in the firmware zip file, the problem is that the tag match is case sensitive, so `[flex]` won't match `TEST.FLEX.DSK`. If you want to use ALL CAPS you will need to edit IMG.CFG and change the line `[flex]` to `[FLEX]`.

**Comment by keirf** [comment] 2020-10-09 18:53
For bonus points see if you can make your own tagged config in IMG.CFG to handle your single-density image (eg. called BLANK.FLEXSS.DSK). As a hint, all cylinders of `[FLEXSS]` will have the same configuration as `[FLEX]`'s cylinder 0.

**Comment by mikewbrantley** [comment] 2020-10-09 18:58
Okay.  I did attach zip file.  Guess I should put it on github next time.  I will make changes to img.cfg and try again.

**Comment by keirf** [comment] 2020-10-09 18:59
Possibly the tag match should be case insensitive. After all FAT is not case sensitive. I'll have a think about that for the next build.

**Comment by mikewbrantley** [comment] 2020-10-09 19:08
I will try that in a few minutes.  I am now running a format on the test.flex.dsk and write went good.  Verify is going good also so far.

**Comment by mikewbrantley** [comment] 2020-10-09 19:13
Format finished good.  I am now copying real floppy drive contents to flashfloppy.  So far, good.  Will work on IMG.CFG for BLANK.FLEXSS.DSK.

**Comment by mikewbrantley** [comment] 2020-10-09 19:52
Copy of complete real floppy to flashfloppy worked great.  I created a tagged config [FLEXSS] in the IMG.CFG and formatted the BLANK.FLEXSS.DSK with no problems.  I am copying all files from real floppy disk to flashfloppy now.  I am including my IMG.CFG zip file with this note.  By the way, BLANK.FLEXXSS.DSK is configured as 80 track, double density.  Thanks for everything Keir.  I don't know how to thank you but just know I appreciate everything you have done.  If I can ever help you in any way, please call on me.
[IMG.zip](https://github.com/keirf/FlashFloppy/files/5357197/IMG.zip)

**Comment by keirf** [comment] 2020-10-09 21:16
Ah looks great! I will be further enhancing this, probably over this weekend:
1. I will make the tags case insensitive
2. I will allow to tag by filesize in addition to (or instead of) nametag. This will allow you to use untagged image names, and the correct config picked out of IMG.CFG by filesize alone, if you want.
3. I will add example configs under examples/host/<host>/IMG.CFG. So in this case perhaps `examples/host/TSC_Flex/IMG.CFG` and we can add all the necessary configs for various image types/sizes there.

**Comment by mikewbrantley** [comment] 2020-10-09 22:27
Sounds great.

-------- Original message --------From: Keir Fraser <notifications@github.com> Date: 10/9/20  5:16 PM  (GMT-05:00) To: keirf/FlashFloppy <FlashFloppy@noreply.github.com> Cc: mikewbrantley <cataula0@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [keirf/FlashFloppy] Per-track format configuration in IMG.CFG (#378) 
Ah looks great! I will be further enhancing this, probably over this weekend:

I will make the tags case insensitive
I will allow to tag by filesize in addition to (or instead of) nametag. This will allow you to use untagged image names, and the correct config picked out of IMG.CFG by filesize alone, if you want.
I will add example configs under examples/host//IMG.CFG. So in this case perhaps examples/host/TSC_Flex/IMG.CFG and we can add all the necessary configs for various image types/sizes there.

**Comment by keirf** [comment] 2020-10-10 09:23
I'll be back in touch in a while with another firmware to try!

**Comment by keirf** [comment] 2020-10-10 10:43
Okay, here it is. Version is bumped to v3.101.
1. TSC Flex now has an IMG.CFG included in the distribution: Simply copy examples/Host/TSC_Flex/IMG.CFG to the root of your USB stick. This should match your DSDD and SSDD images. Let me know if you want any more formats added.
2. You will see that matching is now by filesize rather than filename. You do not need to tag your image names with `flex` any longer.

[ff_378_2.zip](https://github.com/keirf/FlashFloppy/files/5358824/ff_378_2.zip)

**Comment by mikewbrantley** [comment] 2020-10-10 14:36
That worked great.  I even did one for 40 track, DSDD and it worked too.  Thank you again for all the time and effort you have spent on this project.  There will be many people in our Flex User Group thankful for this.

**Comment by keirf** [comment] 2020-10-10 17:27
Okay, all done then! Any formats you'd like to add to the distributed TSC_Flex/IMG.CFG, just let me know. I'm happy to add them, especially if you've tested them and supply them for me simply to append to the file.

Likewise, if you need any extensions to the format (eg to deal with image-file padding) let me know and I'll consider it.

This support as it is will be in the next release (v3.20).

**Comment by keirf** [comment] 2020-10-10 17:51
By the way, here is the latest. Further code tweaks and I've also modified the IMG.CFG so the track format is closer to the HFE you provided earlier in this ticket. Please feel free to test (and extend IMG.CFG) at your convenience. Should work just the same as the previous, hopefully!

[ff_378_3.zip](https://github.com/keirf/FlashFloppy/files/5359590/ff_378_3.zip)

**Comment by mikewbrantley** [comment] 2020-10-10 18:12
This unzipped to v3.19.  Is that correct?  There is already a v3.19.

**Comment by keirf** [comment] 2020-10-10 18:18
Yes I didn't bother to hack the version number on this one. Rest assured it is not the released v3.19

**Comment by mikewbrantley** [comment] 2020-10-10 18:20
Okay.  I will check it out and get back to you.

**Comment by mikewbrantley** [comment] 2020-10-10 18:48
I updated firmware and copied the IMG.CFG but I now get a 31 error.  I put the old IMG.CFG file back on the USB and it works okay.  Any ideas?

**Comment by mikewbrantley** [comment] 2020-10-10 19:03
I noticed on the new IMG.CFG, the tag has flex in it now......[flex::733184].   Old one did not have flex; just file size.

**Comment by keirf** [comment] 2020-10-10 20:06
You didn't copy the correct IMG.CFG. You want the one under `examples/Host/TSC_Flex`.

**Comment by mikewbrantley** [comment] 2020-10-10 20:44
You are correct.  Sorry, I just picked up the first one I saw.  Copied the right one all works great.  Thanks.

**Comment by mikewbrantley** [comment] 2020-10-13 21:52
Hey Keir, I have run into a problem with Flex formatted disk on FlashFloppy when done by different hardware.  I asked someone to check out the FlashFloppy firmware on their system.  They are using SWTPC computer but it has a different Floppy Disk Controller and runs at 1 Mhz instead of 2 Mhz like mine.  I did slow my system to 1 Mhz and it still worked on FlashFloppy fine.  They can format an 80 track, ds, dd floppy on their physical drive but when trying to do the same on the FlashFloppy system, It fails with a disk read error on the verify.  Do you think the IMG.CFG file needs different settings?  Would you like for me to reopen #378 issue or create another one or just let you take a look?  If you want me to send you an HFE dump of his formatted floppy, let me know?  Thanks,
Mike

**Comment by keirf** [comment] 2020-10-14 07:42
The problem is probably write speed to the USB stick amazingly enough.

Perhaps confirm with the logfile firmware (https://github.com/keirf/FlashFloppy/wiki/Logging-To-USB-Drive) or try another USB stick.

Some sticks are fussier about small writes than others. And especially because Flex format has sector interleave, so the small blocks aren't even written in-order into the IMG file. The best solution would be to buffer the track's writes and write out on head movements. This isn't implemented yet.

**Comment by keirf** [comment] 2020-10-14 10:54
The other thing to confirm is that this other machine's Flex really is exactly same format as yours. To do this we'd need to dump of one of his real formatted disks. Eg. using Greaseweazle. Then I could inspect and confirm one way or another.

Or he could do what you did and format an HFE image file? That would be okay too!

**Comment by mikewbrantley** [comment] 2020-10-14 11:20
I will check it out and get back to you.

-------- Original message --------From: Keir Fraser <notifications@github.com> Date: 10/14/20  3:43 AM  (GMT-05:00) To: keirf/FlashFloppy <FlashFloppy@noreply.github.com> Cc: mikewbrantley <cataula0@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [keirf/FlashFloppy] Per-track format configuration in IMG.CFG (#378) 
The problem is probably write speed to the USB stick amazingly enough.
Perhaps confirm with the logfile firmware (https://github.com/keirf/FlashFloppy/wiki/Logging-To-USB-Drive) or try another USB stick.
Some sticks are fussier about small writes than others. And especially because Flex format has sector interleave, so the small blocks aren't even written in-order into the IMG file. The best solution would be to buffer the track's writes and write out on head movements. This isn't implemented yet.

**Comment by mikewbrantley** [comment] 2020-10-14 13:03
Okay.  By the way, I have his machine here with me.  I have tried several versions of Flex on his machine and I get the same results.  The format on the FlashFloppy writes through all 80 tracks and then returns to track 0 and tries to write something and fails on sector B and then sector C and then I stop it by resetting the machine, change FlashFloppy to a different image and then dump the log file that I am including as a zip.  I am also including a zip file containing an HFE image file of a good formatted disk from his machine.  I did change to a different USB stick and got same results.  Thanks for help.

**Comment by mikewbrantley** [comment] 2020-10-14 15:36
Sometimes, gmail blocks attachments so am sending this from different account.
-------- Original message --------From: Mike Brantley <cataula0@gmail.com> Date: 10/14/20  9:02 AM  (GMT-05:00) To: keirf/FlashFloppy <reply@reply.github.com>, keirf/FlashFloppy <FlashFloppy@noreply.github.com> Cc: Mention <mention@noreply.github.com>, Brantley Mike <mikewbrantley@gmail.com> Subject: Re: [keirf/FlashFloppy] Per-track format configuration in IMG.CFG (#378) 


Okay.  By the way, I have his machine here with me.  I have tried 
several versions of Flex on his machine and I get the same results.  The 
format on the FlashFloppy writes through all 80 tracks and then returns to track 
0 and tries to write something and fails on sector B and then sector C and then 
I stop it by resetting the machine, change FlashFloppy to a different image and 
then dump the log file that I am including as a zip.  I am also including a 
zip file containing an HFE image file of a good formatted disk from his 
machine.  I did change to a different USB stick and got same results.  
Thanks for help.


 

From: Keir Fraser 
Sent: Wednesday, October 14, 2020 6:54 AM
To: keirf/FlashFloppy 

Cc: mikewbrantley ; Mention 
Subject: Re: [keirf/FlashFloppy] Per-track format configuration in 
IMG.CFG (#378)
 

The other thing to confirm is that this other machine's Flex really is 
exactly same format as yours. To do this we'd need to dump of one of his real 
formatted disks. Eg. using Greaseweazle. Then I could inspect and confirm one 
way or another.
Or he could do what you did and format an HFE image file? That would be okay 
too!
—You 
are receiving this because you were mentioned.Reply to this email directly, 
view 
it on GitHub, or unsubscribe.

**Comment by keirf** [comment] 2020-10-14 17:42
The attachments probably got stripped off by Github. It is easiest to log into github and attach a file in their issue tracker directly in their website.

**Comment by mikewbrantley** [comment] 2020-10-14 18:24
Okay.  By the way, I have his machine here with me.  I have tried several versions of Flex on his machine and I get the same results.  The format on the FlashFloppy writes through all 80 tracks and then returns to track 0 and tries to write something and fails on sector B and then sector C and then I stop it by resetting the machine, change FlashFloppy to a different image and then dump the log file that I am including as a zip.  I am also including a zip file containing an HFE image file of a good formatted disk from his machine.  I did change to a different USB stick and got same results.  Thanks for help.
[FFLOG.zip](https://github.com/keirf/FlashFloppy/files/5380125/FFLOG.zip)
[Floppy HFE formatted with diff FDC.zip](https://github.com/keirf/FlashFloppy/files/5380127/Floppy.HFE.formatted.with.diff.FDC.zip)

**Comment by keirf** [comment] 2020-10-14 18:46
Okay, there are some format differences. The order of sectors on cylinder 0 is different, which probably doesn't matter. All the other tracks are only 17 sectors, rather than 18: sector 1 is missing on head 0, and sector 22(!) is missing on head 1. But again I'm kind of surprised if it can't deal with extra sectors magically appearing on the track. It would probably just ignore them!

What I hadn't spotted before is that both heads of cylinder 0 have all sectors marked as "head 0". And both heads of all other cylinders have all sectors marked "head 1". Obviously your FDC doesn't care, as I don't replicate this and your system didn't mind. But perhaps his does.

I will see about making a patch to replicate this behaviour.

**Comment by keirf** [comment] 2020-10-14 19:20
Okay, try this. You will also need the IMG.CFG from `examples/Host/TSC_Flex/`, as that has been modified to force the head number.

[ff_378_4.zip](https://github.com/keirf/FlashFloppy/files/5380396/ff_378_4.zip)

**Comment by mikewbrantley** [comment] 2020-10-14 20:15
I’m sorry I did not catch that earlier.  Thanks for help.

**Comment by keirf** [comment] 2020-10-14 20:25
No problem, you now have a patched version, see above ^ :)

**Comment by mikewbrantley** [comment] 2020-10-14 21:07
Great!  I am away from house right now.  Be back in about an hour.  Will get right back to you.  Thanks again.

-------- Original message --------From: Keir Fraser <notifications@github.com> Date: 10/14/20  4:25 PM  (GMT-05:00) To: keirf/FlashFloppy <FlashFloppy@noreply.github.com> Cc: mikewbrantley <cataula0@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [keirf/FlashFloppy] Per-track format configuration in IMG.CFG (#378) 
No problem, you now have a patched version, see above ^ :)

**Comment by mikewbrantley** [comment] 2020-10-15 00:53
Sorry, it took so long to get back to you.  This friends computer stopped working and I had to work on it.  I am sure you are sleeping by now but maybe you can get this in the morning.  The DSDD 80 track worked great.  It formatted and returned to track 0 and verified all 80 tracks and then wrote the boot loader.  Looks good.  I then tried the SSDD 80 track format.  It failed as before...formatted through track 79 and returned to track 0 and failed at sector B and beyond.  Thanks again for working on this.

**Comment by keirf** [comment] 2020-10-15 06:47
Thanks. Try this one. I have modified the firmware, and also you need the new `examples/Host/TSC_Flex/IMG.CFG' too.

[ff_378_5.zip](https://github.com/keirf/FlashFloppy/files/5382900/ff_378_5.zip)

Are you sure by the way that the computer was correctly formatting as single sided? Just a thought. As there'd be no sector B on cylinder 0 (sector B is on the other side!).

Also you'll want to verify these changes on your machine, so we know we're not breaking what we already got working.

**Comment by mikewbrantley** [comment] 2020-10-15 10:35
That worked good for both ssdd and dsdd.  I will get my computer back out and test changes on it.  Will get back a little later.  Thanks again for everything.

**Comment by mikewbrantley** [comment] 2020-10-15 11:10
Excellent work!  It still works on my machine also.  I am really impressed with your skills.  Thank you so much for all you time and effort in making FlashFloppy work with TSC Flex software and different hardware.  Please call on me if I can ever be any help to you.
Mike

**Comment by keirf** [comment] 2020-10-15 11:11
That's great, and thanks for your testing! I am going to do a v3.20 release now.

**Closed by keirf** 2020-10-15 11:11 UTC
