### ISSUE TITLE
Emulating 2 drives at the same time?

### ISSUE THREAD

**Issue by Wierzbowsky** [keirf/FlashFloppy#261] opened 2019-09-04 15:57 UTC
I wonder if it's possible to emulate 2 drives at the same time on the same Gotek device. It would be really swell if 2 disk images could exchange data on the same media. Selection could be done by long pressing left or right buttons (left for the first drive, right for the second drive). If the device can control the DS line, that should be possible.

**Comment by keirf** [comment] 2019-09-05 06:03
This is a duplicate of #36.

**Closed by keirf** 2019-09-05 06:03 UTC
