### ISSUE TITLE
How do you jump the wires on this kind of board? SFRA619

### ISSUE THREAD

**Issue by Cyrus331** [keirf/flashfloppy#911] opened 2024-07-04 01:31 UTC
I recently got a floppy drive. The layout of its circuit board is like this. The chip is STM32F105 but the pin layout at the bottom is different. How do you jump the wires on this kind of board? Have you ever encountered it?
![微信图片_20240704093029](https://github.com/keirf/flashfloppy/assets/98383215/0c312431-566d-4442-80c6-43d4781875f2)
![微信图片_20240704093044](https://github.com/keirf/flashfloppy/assets/98383215/3d45cb0e-9802-4fe5-94d4-77559065b733)

**Comment by keirf** [comment] 2024-08-11 08:07
This is a duplicate of #531. You will see users had success there, but noone has actually documented where they put the jumper wires!

**Closed by keirf** 2024-08-11 08:07 UTC
