### ISSUE TITLE
Ensoniq EPS classic "Disk Drive not ready" via Gotek FF V2.13

### ISSUE THREAD

**Issue by zaxxon-hh** [keirf/FlashFloppy#240] opened 2019-06-15 10:30 UTC
Hi there, first of all a nice Project !

But i have a problem :-(

interface = shugart  host = ensoniq pin02 = nchg pin34 = rdy

I could boot the OS automatically. So far so good.  The first Instrument loads without problem. 

On second i could load the Name by pressing the load button after pressing enter-yes "disk drive not ready" :-(  where i normal should get "pick instrument button"

If i press the rotary knob i can eject the Image and once again it is mounted again...

Now it loads like ist should. All files are converted to HFE V.2

I have played around with pin 2 and 34 values nothing helps....

Any solution which that could bring me closer to a real Floppy ???

**Comment by keirf** [comment] 2019-06-15 10:47
Are those configuration options each on their own line in FF.CFG?
Did you try `pin02 = auto`?

**Comment by keirf** [comment] 2019-06-15 10:52
You shouldn't need to convert to HFE by the way. The `host = ensoniq` option is so that raw sector files get correctly detected to be Ensoniq disk format.

**Comment by zaxxon-hh** [comment] 2019-06-15 11:00
wow you are fast :-)

pin2 auto same result

**Comment by zaxxon-hh** [comment] 2019-06-15 11:02
## FF.CFG: Example FlashFloppy Configuration File

# Place in the root folder or FF/ subfolder of your USB drive.
# Uncommented lines below are the default settings.
# Uncommented options cannot be overridden by settings in other config files.

##
## DRIVE EMULATION

# Floppy-drive interface mode
# shugart: P2=DSKCHG, P34=RDY
# ibmpc: P2=unused, P34=DSKCHG
# ibmpc-hdout: P2=HD_OUT, P34=DSKCHG (not generally needed: prefer 'ibmpc')
# akai-s950: P2=HD_OUT, P34=RDY (Akai S950)
# amiga: P2=DSKCHG, P34=DRIVE_ID (not generally needed: prefer 'shugart')
# jc: JC closed: ibmpc, JC open: shugart
interface = shugart

# Host platform: Improves image-format detection for generic types such as IMG
# acorn: Acorn ADFS
# akai: Akai (S01, S20, S950), Korg, SC Prophet 3000
# casio: Casio (FZ-1)
# dec: DEC (RX33, RX50)
# ensoniq: Ensoniq (ASR, TS, etc)
# fluke: Fluke 9100
# gem: General Music (S2, S3)
# kaypro: Kaypro
# memotech: Memotech
# msx: MSX
# nascom: Nascom
# pc98: NEC PC-98
# pc-dos: PC DOS Format (geometry determined from Bios Parameter Block)
# tandy-coco: Tandy Color Computer (CoCo)
# ti99: TI-99/4A
# uknc: UKNC / DVK Soviet PDP-11
# unspecified: Common default geometries (including IBM PC)
host = ensoniq

# Pins 2 & 34 output (drive->host) manual configuration
# auto: Auto-configure from interface= setting
# nc: Unused/No Connection [eg. if pin is an input (host->drive) on your host]
# low: Always 0 volts (0v)
# high: Always 5 volts (5v)
# rdy: Drive ready (Ready = 0v)
# nrdy: Logical complement of above
# dens: Density mode (High Density = 0v)
# ndens: Logical complement of above
# chg: Disk changed (Changed = 0v)
# nchg: Logical complement of above
# Values: auto, nc, low, high, rdy, nrdy, dens, ndens, chg, nchg
pin02 = auto
pin34 = rdy

config just now from the usb stick copied...

**Comment by keirf** [comment] 2019-06-15 11:14
No difference in behaviour at all when pin02 setting is changed?

**Comment by keirf** [comment] 2019-06-15 11:15
That FF.CFG is hard to read. You actually only need the three setting lines in your config all the comments could be removed

**Comment by keirf** [comment] 2019-06-15 11:15
Also worth a try playing with jumpers. For example try adding an extra jumper at MO. Remove it if it doesn't help

**Comment by zaxxon-hh** [comment] 2019-06-15 11:17
i know the EPS is a diva :-) i have built a Sony MFP 520-1 real Floppy to get work with my EPS...

No , sorry to say noting has changed in behavior

playing around with pin 2 and 34 i remeber that i have had some like "Disk has changed...." message

**Comment by zaxxon-hh** [comment] 2019-06-15 11:19
MO Jumper i have tried and the Hardware mod i have tried PB15 1k Ohm as you pinned in your Hardware mods

**Comment by zaxxon-hh** [comment] 2019-06-15 11:27
i would put point on the pin 34 if i am right the rdy goes to 0V and after it goes stable to 5 V on real Floppy drive....
i am not sure on that but that could be a hint

**Comment by keirf** [comment] 2019-06-15 11:34
If you connected motor to pb15 did you also try `motor-delay` in FF.CFG?

Avoltmeter on pins 2 and 34 of a real working drive may be useful however bear in mind these pins also react to other pins such as select motor and step and thus results can be confusing or misleading. Logic analyser is better but not many people have them.

**Comment by zaxxon-hh** [comment] 2019-06-15 11:35
motor-delay is set to 200

**Comment by zaxxon-hh** [comment] 2019-06-15 11:36
ok sounds like there are no other EPS User out there :-(

**Comment by keirf** [comment] 2019-06-15 11:36
Low then high on pin 34 would sound a bit like disk change. In which case interface=ibmpc or ibmpc-hdout worth trying

**Comment by keirf** [comment] 2019-06-15 11:38
Ask on the Facebook group. Not many other than me look here, it's my bug tracker not a support forum. Eg Chris Poacher and others on that group have broad synth experience.

**Comment by zaxxon-hh** [comment] 2019-06-15 11:42
ibmpc-hdout 
pin02 = nchg
pin34 = rdy

same result "diskdrive not ready"

**Comment by zaxxon-hh** [comment] 2019-06-15 11:43
ok i will grab my Voltmeter....

**Comment by keirf** [comment] 2019-06-15 11:44
pin02 and pin34 settings are overriding the new interface setting. Please set them both to `auto`.

**Comment by zaxxon-hh** [comment] 2019-06-15 11:48
i have the original Floppy drive which i will use for measurment on pin 2 and 34 

stay tuned....

**Comment by zaxxon-hh** [comment] 2019-06-15 12:06
ok first result: 5 V stable on pin 34 . If its reading the directory it goes low 0 V , after stable 5 V . 

if i load the instrument it goes from 5V to low 0V and after the file is in memory it goes back to 5 V !

that looks like that the gotek FF does not that behavior, i am right on that ?

FF does not emulate that right ?

**Comment by zaxxon-hh** [comment] 2019-06-15 12:23
i am not on FB

**Comment by keirf** [comment] 2019-06-15 12:26
That is likely correct behaviour for READY signal. It goes to 0v only when drive is selected and motor is enabled. If you test on FlashFloppy with `motor-delay=200` in FF.CFG, you should see the same (interface=shugart, pin02=auto, pin34=auto). This is why checking one signal at a time gets confusing.

**Comment by keirf** [comment] 2019-06-15 12:28
It all sounds like classic Shugart really, so the problems you see are perplexing.

**Comment by keirf** [comment] 2019-06-15 12:35
Taking a longer view to solving this, get a Saleae logic analyser on Ebay (clones available for cheap) and some grabber probes, and get a trace of real drive on pins 2, 10, 16, 20, 34 (at a minimum). Not much outlay, pretty useful thing to have. Then you can see correct relationship between signals.

**Comment by zaxxon-hh** [comment] 2019-06-15 12:44
ok, if i automount the mage after 2 seconds and that does the same as manually  i don not know whats wrong. 
on the manually way eject and mount again and it work it is not complicated i would say....
that could be a software issue i would like to say...

**Comment by keirf** [comment] 2019-06-15 12:47
Why automount anyway. If you have the third button on your Gotek then disable auto select in FF.CFG

**Comment by zaxxon-hh** [comment] 2019-06-15 12:58
it is more comfortable i would say, by the way that should not be a difference for me on the interface....

but i am not sure on that .... that is something you can tell me...

**Comment by keirf** [comment] 2019-06-15 13:04
Shouldn't make any difference unless host has a minimum time between disk swaps below which it doesn't recognise the disk change? I'm sure there's no difference on the firmware side

**Comment by zaxxon-hh** [comment] 2019-06-15 13:09
mhm, 

autoselect-file-secs = 0

but i does grab the image...

any idea why ?

**Comment by keirf** [comment] 2019-06-15 13:16
Still autoselected after two seconds? Then the config line or even perhaps you'd whole config is not accepted for some reason.

**Comment by zaxxon-hh** [comment] 2019-06-15 13:18
right after 1 second...

**Comment by keirf** [comment] 2019-06-15 13:21
I will confirm the config option behaviour myself later.

**Comment by zaxxon-hh** [comment] 2019-06-15 13:24
i will try a new FF.CFG

**Comment by keirf** [comment] 2019-06-15 13:35
Confirmed `autoselect-file-secs = 0` works correctly in v2.13 (ie disables autoselect).

You need to get that sorted as obviously none of your other config settings may be working either. In which case all your config attempts this far have been time wasted. This is a config option with a nice obvious effect for you to get fixed.

**Comment by zaxxon-hh** [comment] 2019-06-15 14:16
OK! got it sorted Confirmed autoselect-file-secs = 0 works correctly now

Fault is the same ! after load the O.S. rotary pressing eject ok step over to the next instrument pressing rotary it mount and load... 

eject on rotary step over to the next instrument mount "disk drive not ready" again eject after mount and it loads....

**Comment by zaxxon-hh** [comment] 2019-06-15 15:04
Pin2 behave like Pin 34 no access 5V stable if reading the directory or loading the instrument it goes on low 0V 

is that what the FF output pin 2  is doing ?

**Comment by keirf** [comment] 2019-06-15 15:36
What size are the eps disk images?

**Comment by zaxxon-hh** [comment] 2019-06-15 15:38
800 kb

**Comment by keirf** [comment] 2019-06-15 15:42
Are we back to interface=shugart pin02=nchg pin34=rdy?

**Comment by zaxxon-hh** [comment] 2019-06-15 15:43
if i set pin 2 on 5 V via FF.CFG stable it just boot the OS an the EPS don not read again....nothing happens to disk

in fact every disk change will generate in real floppy a 5V to 0V change. 

that let the EPS read the Floppy again...

if that does not happen that could give an error like "disk drive not ready" i would say 

correct me if i am wrong on that...

**Comment by zaxxon-hh** [comment] 2019-06-15 15:44
yes that is what actual use 

interface=shugart pin02=nchg pin34=rdy

but i see pin 2 does not change like the real floppy does....

**Comment by keirf** [comment] 2019-06-15 15:45
Try `pin02=low`

**Comment by zaxxon-hh** [comment] 2019-06-15 15:47
btw the Pin 34 looks like as you told me,(shugart compliant) so i would say it is ok

**Comment by keirf** [comment] 2019-06-15 15:50
Going to 0v on disk eject would be `pin02=chg` behaviour but then it will go back to 5v on next head step (pulse on pin 20). It could be a weird disk-change signal on pin 2 but I see no documentation of that online for EPS

**Comment by zaxxon-hh** [comment] 2019-06-15 15:53
ok tested Pin2 = low just give me always an "disk drive not ready "

**Comment by zaxxon-hh** [comment] 2019-06-15 15:54
ok sorry the OS boots up forgotten to say

**Comment by zaxxon-hh** [comment] 2019-06-15 15:57
i will check that ! if PIN2 goes back to 5 V i do not think so...

i will use PIN2 = auto so the interface should do the work without using the FF.CFG

right ?

**Comment by keirf** [comment] 2019-06-15 16:02
That is right pin02=auto means the pin behaviour is driven by the interface setting. Which for shugart is same as pin02=chg

**Comment by zaxxon-hh** [comment] 2019-06-15 16:11
ok my result: OS boots correct 
PIN 2 = auto
Pin 2 holds 5V stable if i eject or not but it stays on 5V on reading the disk in message with "disk drive not ready" 

in my opinion that is not EPS compliant....

**Comment by keirf** [comment] 2019-06-15 16:21
Yes this is why a logic analyser trace really is needed, so we can see relationship between the signals. I could actually characterise EPS pin 2 behaviour then.

**Comment by zaxxon-hh** [comment] 2019-06-15 16:22
i have an service manual for the EPS but to get information about is horrible. 

you are right documentation is a mess about that...

**Comment by keirf** [comment] 2019-06-15 16:23
Service manual may or may not help. It can be as brief as "replace drive with such and such model".

**Comment by zaxxon-hh** [comment] 2019-06-15 16:26
haha right 

but why is that so weird ? i have an Sony Floppy moded to work in it like hell....

**Comment by zaxxon-hh** [comment] 2019-06-15 16:29
the only reason i need to change to an Gotek is the old disks are no more readable due age 

i have about 70% that are just damaged now :-(

**Comment by keirf** [comment] 2019-06-15 16:30
For example some drives have a disk change reset signal from host to drive at pin 1. Then pin 2 would not transition from 0 back to 5v until pin 1 is asserted. Its rare though. Um and I think some other drives have disk change which ignores whether the drive is selected or not (ie that pin is not gated). Again, rare. But if nothing else is working, and you believe the host and cable is OK (eg they work with real drive)...

**Comment by keirf** [comment] 2019-06-15 16:31
If I could get a real working drive I can work out what's going on. But I figure you are mainland Europe not UK?

**Comment by zaxxon-hh** [comment] 2019-06-15 16:32
i am in Germany yes

**Comment by keirf** [comment] 2019-06-15 16:34
I suggest get a logic analyser and trace the drive. Or send it to me and I will do so. Perhaps EPS needs further support in the firmware.

**Comment by zaxxon-hh** [comment] 2019-06-15 16:37
is it worth to help other user if i send you an real drive ?

or iam the only one who try to get it run ?

**Comment by keirf** [comment] 2019-06-15 16:38
I checked with my go to guy and he tells me he and a friend of his have no luck either. So I guess the wiki is wrong and this is a more general unsolved problem.

**Comment by keirf** [comment] 2019-06-15 16:42
I am happy to give it a going over at the circuit level and also take signal traces if you send it to me.

**Comment by zaxxon-hh** [comment] 2019-06-15 16:42
ok i will help if you want to have a look at...

**Comment by keirf** [comment] 2019-06-15 16:43
Does the service manual have a circuit schematic at all? The pin labelling in the floppy header would be interesting if so.

**Comment by zaxxon-hh** [comment] 2019-06-15 16:43
you will get an real Floppy from me with the OS boot disk :-)

**Comment by zaxxon-hh** [comment] 2019-06-15 16:44
schematic no problem

**Comment by zaxxon-hh** [comment] 2019-06-15 16:45
[ensoniq_eps_eps-m_sm.pdf](https://github.com/keirf/FlashFloppy/files/3293344/ensoniq_eps_eps-m_sm.pdf)

**Comment by keirf** [comment] 2019-06-15 16:46
Email me keir.xen@gmail.com to arrange things.

**Comment by zaxxon-hh** [comment] 2019-06-15 16:47
ok first i give you the Service manual and the schematic here

**Comment by zaxxon-hh** [comment] 2019-06-15 16:49
[eps-sch.pdf](https://github.com/keirf/FlashFloppy/files/3293348/eps-sch.pdf)

**Comment by zaxxon-hh** [comment] 2019-06-15 16:50
ok just placed here , so other users can get them too .-)

**Comment by zaxxon-hh** [comment] 2019-06-15 16:51
thank you for your help , i appriciate that much...

**Comment by keirf** [comment] 2019-06-15 17:06
Okay the floppy header has no strange extra signals on pin 1, or anything. Drive-select and motor-on are always asserted together. Pin 2 is called /DSKCH, nothing odd about that, on a Shugart drive. Pin 34 is called /DSTAT, I've never heard of /RDY being called that, but it could just be an idiosyncracy of this schematic.

Those two signals connect to a UART and from there are being controlled by software so no more can be determined from the schematic.

**Comment by zaxxon-hh** [comment] 2019-06-15 17:10
right but the signals are inverted due LS04....

**Comment by keirf** [comment] 2019-06-15 17:21
Yes signals are always active-low at the floppy interface. Almost always anyway. Because the floppy interface is designed to be open collector bus.

**Comment by zaxxon-hh** [comment] 2019-06-15 17:22
lol, He just could be my brother .....

How to modify a SONY mpf920 floppy drive
Hello everyone. I'm trying to make a SONY MPF920 Z/161 to work on Ensoniq EPS 16+ sampler.

It must be converted from PC to Shugart interface. So I've followed the Commodore Amiga's mod. Changed drive select 1 to 0. Then cutted pin 34 trace, and connected what previously went to pin 34 to pin 2(disk change). Then connected pin 14 from BA6986FS to pin 34, supposedly ''ready'' signal.

At first it perfectly loads the OS. But when I put an instruments diskette, when i press the navigate or load buttons, the ''change disk'' signal (pin 2) goes to 0 volts, so it reads and load from 0 the diskette each time, preventing to navigate it. If I want to load the only instrument it shows, it says ''disk drive not ready''.

I have made some reverse engineering with the original FDD (Panasonic JU-257 303P), and the problem is change disk signal going to 0. In the original drive it stays at 5 volts. I dont know if it is a disk change or ready signal problem.

so it is strange to get an Floppy if real or not to get run in the EPS "diva"

**Comment by zaxxon-hh** [comment] 2019-06-15 17:24
for today i am done :-) 

thank you for your time you did spent for me today...

**Comment by keirf** [comment] 2019-06-15 17:25
Have you tried `pin02=high`?

**Comment by zaxxon-hh** [comment] 2019-06-15 17:35
yes i have done that ,you can read that somewhere in the post....

here it is ...

if i set pin 2 on 5 V via FF.CFG stable it just boot the OS and the EPS do not read again....nothing happens to disk

the disk change is not be recognized by EPS i would think....

i can mount different Disk without success... no directory reading again...

**Comment by zaxxon-hh** [comment] 2019-06-15 17:37
that is what want to put fucus on...

Pin2 i would believe is the key of success...

**Comment by zaxxon-hh** [comment] 2019-06-15 17:43
Sorry focus i mean...

so it need to be change from high to low before or on  every disk access....

**Comment by zaxxon-hh** [comment] 2019-06-15 17:44
ok for today we have done enough :-)

**Comment by keirf** [comment] 2019-06-16 08:35
Perhaps DSKCHG isn't gated by drive-select. Here's a firmware which implements that. It requires in FF.CFG: `pin02=chg1`.

[ff_240_1.zip](https://github.com/keirf/FlashFloppy/files/3293941/ff_240_1.zip)

An alternative to this firmware would be to jumper drive select to Ground. Jumper S0 across to JB would achieve this making drive permanently selected.

**Comment by zaxxon-hh** [comment] 2019-06-16 19:26
wow, that ist very nice, Thank You ! I will test that....
Today i have been outside :-)

**Comment by zaxxon-hh** [comment] 2019-06-17 13:26
give some more days to check that out please...

just some busy days in front of me....

**Comment by zaxxon-hh** [comment] 2019-06-20 09:53
ok Keir, today i have time to check that, let us go on :-)

**Comment by zaxxon-hh** [comment] 2019-06-20 10:15
ok Dude seems to come closer :-)

FF udate done .

FF.CFG pin02=chg1

OS boot up...

1st instrument does load good

2nd instrument "Disk Drive not Ready" just chose another one after ...

3rd instrument loads good

4th instrument "Disk Drive not Ready" chose another one...

so the first ok 
next not 

every 2nd try seems to work well..

any ideas why that just happen every sencond try only ?

**Comment by keirf** [comment] 2019-06-20 11:52
Isn't that a lot like how it behaved before?

**Comment by keirf** [comment] 2019-06-20 11:52
Probably will just wait for a logic analyser trace

**Comment by zaxxon-hh** [comment] 2019-06-20 12:25
seems like that, 
ok i will contact you in a few days how to send you a real floppy drive for a logic analyser trace.that you can do ...

**Comment by keirf** [comment] 2019-06-20 13:31
Perahps one last thing to try is permanently selecting the drive, so no output is ever gated. You can do that by placing the drive-select jumper horizontally across S0 and JB (the pins closest to the S0,JB lettering, and thus furthest from the 34-pin connector).

**Comment by keirf** [comment] 2019-06-25 11:53
Another suggestion: Firmware update to the alt/io-test firmware (in that folder in FlashFloppy distribution). Use a jumper wire to test that pins 2 and 34 work (you can jumper them one at a time to an input: eg pin 32. This is all done with the Gotek disconnected except for power (eg. power via USB-A cable).

https://github.com/keirf/FlashFloppy/wiki/Testing-IO-Pins

**Comment by keirf** [comment] 2019-06-25 12:44
Okay, a brand new idea. Perhaps I haven't been deasserting DSKCHG in the usual way all this time. Most drives seem to deassert on the trailing edge of a step pulse only. So I have knocked up a firmware which matches that behaviour. It is worth a try!

[ff_dskchg_1.zip](https://github.com/keirf/FlashFloppy/files/3325292/ff_dskchg_1.zip)

**Comment by keirf** [comment] 2019-06-25 14:08
And if that fails, here is another, which allows you to automatically deassert dskchg after a short time. You should try the following in FF.CFG: `chgrst = delay-3`

Please also revert to: interface=shugart pin02=auto pin34=auto (ie. default Shugart).

[ff_dskchg_2.zip](https://github.com/keirf/FlashFloppy/files/3325634/ff_dskchg_2.zip)

**Comment by zaxxon-hh** [comment] 2019-06-25 16:07
wow. you have been busy.... very cool...
i am some days away i could check that later  sorry

i will let you know if i am back.....

**Comment by keirf** [comment] 2019-06-25 16:17
I have put the call out and I think others will check too. Anyway it will wait fine til you're back. Thanks!

**Comment by keirf** [comment] 2019-07-03 07:54
Are you around to be able to do more testing yet?

**Comment by zaxxon-hh** [comment] 2019-07-03 15:32
Hey Keir, no sorry i am back in my job yet so the time is busy now  at weekend possible i think 

i am sorry

any check from user users heard about ?

**Comment by zaxxon-hh** [comment] 2019-07-03 15:36
other users sorry

**Comment by keirf** [comment] 2019-07-03 16:12
Not yet. Weekend sounds great if you have time. Thanks!

**Comment by zaxxon-hh** [comment] 2019-07-07 08:55
ok let us see what we have ...

**Comment by zaxxon-hh** [comment] 2019-07-07 09:07
The update ff_dskchg_1.zip does not Update the FF error [E02]

**Comment by zaxxon-hh** [comment] 2019-07-07 09:16
tried another usb stick now it goes on...

**Comment by keirf** [comment] 2019-07-07 09:21
Okay thank you. I think ff_dskchg_2.zip and the changes to FF.CFG are the best bet. Especially `chgrst=delay-3`.

**Comment by zaxxon-hh** [comment] 2019-07-07 09:24
Keir !!! First quick look seems to work !

chgrst = delay-3
interface=shugart
pin02=auto
pin34=auto
This is standard Shugart, except DSKCHG will automatically reset after a short delay.

ff_dskchg_2.zip

let me do some more in deep work on that :-)

looks like the key for that issue...

Thanks for the moment...

**Comment by zaxxon-hh** [comment] 2019-07-07 09:33
i just hope some other users can agree with me ?

**Comment by keirf** [comment] 2019-07-07 10:12
Well that would be nice ;) But it has been a couple of weeks and no joy. Chris Poacher has a contact who will do some further testing soon. However I am confident this is the fix, and happy to apply this fix to next v3.x release, and change the documentation for Ensoniq EPS in the wiki (I will remove the stuff about pin02=nchg and instead document the possible need for v3.3a+ and `chgrst=delay-3`.

**Comment by zaxxon-hh** [comment] 2019-07-07 10:36
you can be sure that i am happy with the result if everthing work well. 

i will post a final result in some days where i will put everthing together mods and others what i have done. 

i appreciate your work that you have done for us to get it work....

Thanks Keir !

i will put now everthing together :-) And do some testing ...

**Comment by keirf** [comment] 2019-07-08 04:56
This is now committed to master and the wiki is updated:
https://github.com/keirf/FlashFloppy/wiki/FF.CFG-Configuration-File
https://github.com/keirf/FlashFloppy/wiki/Host-Platforms#ensoniq

This will be supported in forthcoming release v3.3a.

**Closed by keirf** 2019-07-08 04:56 UTC

**Comment by charlietear** [comment] 2019-07-11 10:34
Just wanted to extend my thanks here, I had the same issue with a new Gotek, inside my EPS16 Plus...

This sorted it perfectly. Thanks both of you, will contribute to the project.

**Comment by iamdjaj** [comment] 2020-06-13 16:34
This worked for my EPS.  Thank you!
