### ISSUE TITLE
SCL Images support

### ISSUE THREAD

**Issue by merlinkv** [keirf/FlashFloppy#151] opened 2018-08-07 11:31 UTC
Hello Keirf.

It's possible to add direct support for SCL files?

I have a clon of the ZX Spectrum Beta Disk interface and most of the apps and games are in SCL format.

Thanks & Best Regards

**Comment by keirf** [comment] 2018-08-07 11:51
Duplicate of #145

**Closed** 2018-08-07 11:51 UTC
